@startuml diagramaEnaFood
class Produto{
    - titulo: String
    - descricao: String
}

class Cliente{
    - nome de usuário: String
}

class Endereço {
    - rua: String
    - número: Int
    - bairro: Bairro
    - cidade: Cidade
    - estado: UF
    - cep: String
}

class UF {
    - sigla: String
    - nome: String
}

class Cidade{
    - nome: String
}

class Bairro {
    - nome: String
}

class Menu{}

class Entregador{}

class Fornecedor{}


class Pagamento{}

class Pedido{}

class Entrega{}

UF *-- "*" Cidade 
Cidade *-- "*" Bairro
Cliente "1" -- "1..*" Endereço
Cliente "1" -- "1" Endereço : padrão

@enduml
